# AI Audio Upscaler Pro - CI/CD Pipeline
# Comprehensive production-ready pipeline with security, testing, and deployment

name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags: ['v*']
  pull_request:
    branches: [main, develop]

env:
  REGISTRY: aiupscaleracr.azurecr.io
  IMAGE_NAME: ai-audio-upscaler
  AZURE_RESOURCE_GROUP: ai-upscaler-rg
  AKS_CLUSTER: ai-upscaler-aks
  AZURE_REGION: eastus

jobs:
  # Security and Code Quality Checks
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Run Bandit security linter
        run: |
          pip install bandit[toml]
          bandit -r app/ -f json -o bandit-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            trivy-results.sarif
            bandit-report.json

  # Code Quality and Linting
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy pytest pytest-cov

      - name: Code formatting (Black)
        run: black --check --diff app/ tests/

      - name: Import sorting (isort)
        run: isort --check-only --diff app/ tests/

      - name: Linting (Flake8)
        run: flake8 app/ tests/ --max-line-length=100

      - name: Type checking (MyPy)
        run: mypy app/ --ignore-missing-imports

  # Unit and Integration Tests
  test:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio

      - name: Run tests with coverage
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:testpass@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379/0
          ENVIRONMENT: test
          JWT_SECRET_KEY: test-secret-key
        run: |
          pytest tests/ -v --cov=app --cov-report=xml --cov-report=html

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: |
            coverage.xml
            htmlcov/

  # Build Docker Images
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [security-scan, code-quality, test]
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Run Trivy security scan on image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-image-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-image-results.sarif'

  # Infrastructure Validation
  infrastructure-validation:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        run: |
          cd terraform/
          terraform fmt -check

      - name: Terraform Init
        run: |
          cd terraform/
          terraform init -backend=false

      - name: Terraform Validate
        run: |
          cd terraform/
          terraform validate

      - name: Terraform Plan (Dry Run)
        if: github.event_name == 'pull_request'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          cd terraform/
          terraform init
          terraform plan -no-color > plan.out

      - name: Comment Terraform Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('terraform/plan.out', 'utf8');
            const maxGitHubBodyCharacters = 65536;

            function chunkSubstr(str, size) {
              const numChunks = Math.ceil(str.length / size)
              const chunks = new Array(numChunks)
              for (let i = 0, o = 0; i < numChunks; ++i, o += size) {
                chunks[i] = str.substr(o, size)
              }
              return chunks
            }

            const planChunks = chunkSubstr(plan, maxGitHubBodyCharacters);

            for (let i = 0; i < planChunks.length; i++) {
              const output = `### Terraform Plan Part ${i + 1}

            \`\`\`terraform
            ${planChunks[i]}
            \`\`\`

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Workflow: \`${{ github.workflow }}\`*`;

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              });
            }

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build, infrastructure-validation]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: staging
      url: https://staging.aiupscaler.com
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}-staging

      - name: Deploy to AKS Staging
        run: |
          # Update image tag in deployment manifests
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" k8s/staging/deployment.yaml

          # Apply Kubernetes manifests
          kubectl apply -f k8s/staging/ --namespace=ai-upscaler-staging

          # Wait for rollout
          kubectl rollout status deployment/ai-audio-upscaler-api -n ai-upscaler-staging --timeout=600s
          kubectl rollout status deployment/ai-audio-upscaler-worker -n ai-upscaler-staging --timeout=600s

      - name: Run smoke tests
        run: |
          # Wait for service to be ready
          sleep 30

          # Get service endpoint
          STAGING_URL=$(kubectl get service ai-audio-upscaler-api-lb -n ai-upscaler-staging -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

          # Run basic health check
          curl -f http://$STAGING_URL/health || exit 1
          curl -f http://$STAGING_URL/health/ready || exit 1

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, infrastructure-validation]
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/v')
    environment:
      name: production
      url: https://aiupscaler.com
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER }}

      - name: Deploy Infrastructure Updates
        if: contains(github.event.head_commit.message, '[deploy-infra]')
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          cd terraform/
          terraform init
          terraform apply -auto-approve

      - name: Blue-Green Deployment
        run: |
          # Update image tag in deployment manifests
          sed -i "s|IMAGE_TAG|${{ github.sha }}|g" k8s/production/deployment.yaml

          # Deploy new version (blue-green strategy)
          kubectl apply -f k8s/production/ --namespace=ai-upscaler

          # Wait for new deployment to be ready
          kubectl rollout status deployment/ai-audio-upscaler-api -n ai-upscaler --timeout=900s
          kubectl rollout status deployment/ai-audio-upscaler-worker -n ai-upscaler --timeout=900s

      - name: Production Health Check
        run: |
          # Wait for service to be fully ready
          sleep 60

          # Get production endpoint
          PROD_URL=$(kubectl get service ai-audio-upscaler-api-lb -n ai-upscaler -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

          # Comprehensive health checks
          curl -f http://$PROD_URL/health || exit 1
          curl -f http://$PROD_URL/health/ready || exit 1
          curl -f http://$PROD_URL/health/metrics || exit 1

          # Test API endpoints
          curl -f http://$PROD_URL/api/v1/health || exit 1

      - name: Run Integration Tests
        run: |
          # Run production integration test suite
          pytest tests/integration/ --env=production --url=$PROD_URL

      - name: Notify Deployment Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: success
          channel: '#deployments'
          text: |
            🚀 Production deployment successful!
            Version: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Rollback on Failure
        if: failure()
        run: |
          echo "Deployment failed, rolling back..."
          kubectl rollout undo deployment/ai-audio-upscaler-api -n ai-upscaler
          kubectl rollout undo deployment/ai-audio-upscaler-worker -n ai-upscaler

          # Wait for rollback
          kubectl rollout status deployment/ai-audio-upscaler-api -n ai-upscaler --timeout=300s
          kubectl rollout status deployment/ai-audio-upscaler-worker -n ai-upscaler --timeout=300s

  # Database Migrations
  database-migration:
    name: Database Migration
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[migrate-db]')
    environment:
      name: production-db
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install alembic asyncpg psycopg2-binary

      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: |
          # Run migrations
          alembic upgrade head

      - name: Verify Migration Success
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: |
          # Check current migration version
          alembic current

  # Performance Testing
  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Run Performance Tests
        run: |
          k6 run tests/performance/load-test.js
          k6 run tests/performance/stress-test.js

      - name: Upload Performance Results
        uses: actions/upload-artifact@v3
        with:
          name: performance-results
          path: performance-results.json

  # Security Post-Deployment Scan
  security-post-deploy:
    name: Post-Deployment Security Scan
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://aiupscaler.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Upload ZAP results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: zap-results
          path: report_html.html

  # Cleanup
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [deploy-production, performance-test, security-post-deploy]
    if: always()
    steps:
      - name: Clean up old images
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete old container images
        run: |
          # Keep last 10 images, delete older ones
          az acr repository show-tags --name aiupscaleracr --repository ${{ env.IMAGE_NAME }} --output table
          OLD_IMAGES=$(az acr repository show-tags --name aiupscaleracr --repository ${{ env.IMAGE_NAME }} --orderby time_desc --output tsv --query "[10:].name")

          for IMAGE in $OLD_IMAGES; do
            echo "Deleting old image: $IMAGE"
            az acr repository delete --name aiupscaleracr --image "${{ env.IMAGE_NAME }}:$IMAGE" --yes
          done